### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by danieldraper** [Najtmare/sweet-alert-rails#4]
Looks like there is a problem with 0.0.9 `Uncaught ReferenceError: exports is not defined` I assume this is related to ES6 are there additional steps to make this work with Rails 4.2 that have not been documented?

**Comment by udl** [comment]
having the same issue

**Comment by danieldraper** [comment]
@udl I would recommend using http://limonte.github.io/sweetalert2/ it is actively maintained. It is mostly backwards compatible with a few minor differences like the way inputs work.

**Comment by Najtmare** [comment]
Hi.

Sorry for the delayed response. Imo it would be best to use rails-assets.org for something like sweet-alert or other alike JS libs. Reason is everything gets updated almost the minute a new version is released.

**Comment by udl** [comment]
Thx for the hints!
